# Generated by Django 5.0.6 on 2024-08-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='about myself', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('content', models.TextField()),
                ('additional_content', models.TextField(blank=True, null=True)),
                ('button_text', models.CharField(default='More Info', max_length=50)),
                ('button_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
