# Generated by Django 5.0.6 on 2024-08-12 09:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_author_comment_name_alter_tag_name_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='message',
        ),
        migrations.AddField(
            model_name='comment',
            name='subject',
            field=models.CharField(default=0.0008176614881439084, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
